version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  matrix:
    - TARGET: neko
    - TARGET: node
    - TARGET: js
    - TARGET: flash
    - TARGET: cpp
    - TARGET: cs
    - TARGET: java

matrix:
  fast_finish: false

branches:
  only:
    - develop

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.2.0 -y
  - cinst haxe --version 3.4.7 --ignore-dependencies -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib git hxmake https://github.com/eliasku/hxmake.git
  - haxelib dev hotmem .

build: off

test_script:
  - haxelib run hxmake test --override-test-target="%TARGET%"
